In [1]:
import pandas as pd

In [2]:
import html5lib

In [3]:
matches = pd.read_csv("matches.csv", index_col = 0)

In [4]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2023,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2023,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2023,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2023,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2023,Liverpool

In [5]:
matches.shape

(1540, 27)

In [6]:
matches["team"].value_counts()

team
Liverpool                   96
Crystal Palace              76
Southampton                 76
Leeds United                76
Leicester City              76
Everton                     76
West Ham United             76
Wolverhampton Wanderers     76
Manchester City             76
Chelsea                     76
Brentford                   76
Tottenham Hotspur           76
Aston Villa                 76
Brighton and Hove Albion    76
Newcastle United            76
Manchester United           76
Arsenal                     76
Fulham                      38
Bournemouth                 38
Nottingham Forest           38
Burnley                     38
Watford                     38
Norwich City                38
Name: count, dtype: int64

In [7]:
matches[matches["team"] == "Liverpool"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2023,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2023,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2023,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2023,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2023,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2022-04-30,12:30,Premier League,Matchweek 35,Sat,Away,W,1.0,0.0,Newcastle Utd,...,Match Report,NaN,24.0,10.0,17.7,2.0,0,0,2022,Liverpool
57,2022-05-07,19:45,Premier League,Matchweek 36,Sat,Home,D,1.0,1.0,Tottenham,...,Match Report,NaN,22.0,3.0,19.6,1.0,0,0,2022,Liverpool
58,2022-05-10,20:00,Premier League,Matchweek 33,Tue,Away,W,2.0,1.0,Aston Villa,...,Match Report,NaN,17.0,5.0,17.0,2.0,0,0,2022,Liverpool
60,2022-05-17,19:45,Premier League,Matchweek 37,Tue,Away,W,2.0,1.0,Southampton,...,Match Report,NaN,24.0,5.0,18.6,0.0,0,0,2022,Liverpool
61,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3.0,1.0,Wolves,...,Match Report,NaN,29.0,7.0,15.6,0.0,0,0,2022,Liverpool

In [8]:
matches["round"].value_counts()

round
Matchweek 1     41
Matchweek 12    41
Matchweek 2     41
Matchweek 19    41
Matchweek 18    41
Matchweek 17    41
Matchweek 16    41
Matchweek 15    41
Matchweek 14    41
Matchweek 13    41
Matchweek 20    41
Matchweek 11    41
Matchweek 6     41
Matchweek 10    41
Matchweek 4     41
Matchweek 5     41
Matchweek 3     41
Matchweek 7     41
Matchweek 8     41
Matchweek 9     41
Matchweek 31    40
Matchweek 32    40
Matchweek 37    40
Matchweek 36    40
Matchweek 35    40
Matchweek 28    40
Matchweek 34    40
Matchweek 33    40
Matchweek 25    40
Matchweek 30    40
Matchweek 29    40
Matchweek 27    40
Matchweek 26    40
Matchweek 24    40
Matchweek 23    40
Matchweek 22    40
Matchweek 21    40
Matchweek 38    40
Name: count, dtype: int64

In [9]:
matches["date"] = pd.to_datetime(matches["date"])

In [10]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [11]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [12]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [13]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [14]:
matches["day_code"] = matches["date"].dt.dayofweek

In [15]:
matches["target"] = (matches["result"] == "W").astype("int")

In [16]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,0.0,0,0,2023,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,1.0,0,1,2023,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,1.0,0,0,2023,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,0.0,0,0,2023,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,0.0,0,0,2023,Liverpool,0,24,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0.0,2.0,Aston Villa,...,0.0,0,0,2022,Norwich City,0,1,15,5,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0.0,4.0,West Ham,...,1.0,0,0,2022,Norwich City,1,23,14,6,0
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0.0,3.0,Leicester City,...,0.0,0,0,2022,Norwich City,0,11,19,2,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1.0,1.0,Wolves,...,0.0,0,0,2022,Norwich City,0,24,14,6,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0.0,5.0,Tottenham,...,0.0,0,0,2022,Norwich City,1,21,16,6,0

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split =10, random_state=1)

In [19]:
train = matches[matches["date"] < '2023-04-01']

In [20]:
train

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,1,1,2023,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,0.0,0,0,2023,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,1.0,0,0,2023,Manchester City,0,16,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,0.0,0,0,2023,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,0.0,0,0,2023,Manchester City,1,18,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0.0,2.0,Aston Villa,...,0.0,0,0,2022,Norwich City,0,1,15,5,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0.0,4.0,West Ham,...,1.0,0,0,2022,Norwich City,1,23,14,6,0
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0.0,3.0,Leicester City,...,0.0,0,0,2022,Norwich City,0,11,19,2,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1.0,1.0,Wolves,...,0.0,0,0,2022,Norwich City,0,24,14,6,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0.0,5.0,Tottenham,...,0.0,0,0,2022,Norwich City,1,21,16,6,0

In [21]:
test = matches[matches["date"] > '2023-04-01']

In [22]:
test

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,0.0,0,0,2023,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,1.0,0,1,2023,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,1.0,0,0,2023,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,0.0,0,0,2023,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,0.0,0,0,2023,Liverpool,0,24,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,0.0,0,0,2023,Southampton,0,16,14,6,0
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,0.0,1,1,2023,Southampton,0,18,20,0,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,0.0,0,0,2023,Southampton,1,9,15,5,0
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,1.0,0,0,2023,Southampton,0,4,14,6,0
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,1.0,0,0,2023,Southampton,1,12,16,6,0

In [23]:
test.to_csv("test.csv")

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
acc = accuracy_score(test["target"], preds)

In [29]:
acc

0.5973451327433629

In [30]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [64]:
combined

,actual,predicted,date,team,opponent,result,new_team
64,0,0,2023-04-09,Arsenal,Liverpool,D,Arsenal
65,0,1,2023-04-16,Arsenal,West Ham,D,Arsenal
66,0,0,2023-04-21,Arsenal,Southampton,D,Arsenal
67,0,0,2023-04-26,Arsenal,Manchester City,L,Arsenal
68,1,0,2023-05-02,Arsenal,Chelsea,W,Arsenal
...,...,...,...,...,...,...,...
1466,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
1467,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
1468,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves
1469,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves
1470,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves

In [31]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           103  27
1            64  32

In [32]:
from sklearn.metrics import precision_score

In [33]:
precision_score(test["target"], preds)

0.5423728813559322

In [34]:
grouped_matches = matches.groupby("team")

In [35]:
group = grouped_matches.get_group("Manchester City")

In [36]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,1,1,2023,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,0.0,0,0,2023,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,1.0,0,0,2023,Manchester City,0,16,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,0.0,0,0,2023,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,0.0,0,0,2023,Manchester City,1,18,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4.0,0.0,Leeds United,...,0.0,0,0,2022,Manchester City,0,10,17,5,1
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5.0,0.0,Newcastle Utd,...,1.0,0,0,2022,Manchester City,1,16,16,6,1
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5.0,1.0,Wolves,...,0.0,0,0,2022,Manchester City,0,24,20,2,1
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2.0,2.0,West Ham,...,2.0,0,1,2022,Manchester City,0,23,14,6,0
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3.0,2.0,Aston Villa,...,1.0,0,0,2022,Manchester City,1,1,16,6,1

In [37]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

In [38]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [39]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [40]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,5,1,3.333333,0.333333,19.666667,6.000000,16.866667,0.666667,0.000000,0.000000
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,5,0,3.666667,0.000000,22.000000,7.333333,15.866667,0.333333,0.000000,0.000000
8,2021-09-25,12:30,Premier League,Matchweek 6,Sat,Away,W,1.0,0.0,Chelsea,...,5,1,2.000000,0.000000,22.000000,6.333333,15.166667,0.333333,0.000000,0.000000
10,2021-10-03,16:30,Premier League,Matchweek 7,Sun,Away,D,2.0,2.0,Liverpool,...,6,0,0.666667,0.000000,18.666667,4.000000,15.933333,0.333333,0.000000,0.000000
11,2021-10-16,15:00,Premier League,Matchweek 8,Sat,Home,W,2.0,0.0,Burnley,...,5,1,1.000000,0.666667,14.333333,2.333333,16.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,...,5,1,3.000000,0.666667,13.666667,8.000000,15.433333,0.000000,0.333333,0.333333
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3.0,0.0,Everton,...,6,1,2.333333,0.666667,14.666667,7.000000,16.366667,0.666667,0.333333,0.666667
56,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1.0,0.0,Chelsea,...,6,1,2.666667,0.333333,14.000000,5.666667,18.100000,1.333333,0.000000,0.333333
57,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1.0,1.0,Brighton,...,2,0,2.000000,0.333333,13.666667,4.000000,18.933333,1.333333,0.000000,0.333333
58,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0.0,1.0,Brentford,...,6,0,1.666667,0.333333,12.333333,3.333333,17.333333,0.666667,0.000000,0.000000

In [41]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [42]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2021-09-11  15:00  Premier League   Matchweek 4
                        5  2021-09-18  15:00  Premier League   Matchweek 5
                        7  2021-09-26  16:30  Premier League   Matchweek 6
                        8  2021-10-02  17:30  Premier League   Matchweek 7
                        9  2021-10-18  20:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Premier League  Matchweek 34
                        40 2023-05-06  15:00  Premier League  Matchweek 35
                        41 2023-05-13  15:00  Premier League  Matchweek 36
                        42 2023-05-20  15:00  Premier League  Matchweek 37
                        43 2023-05-28  16:30  Premier League  Matchweek 38

                            day venue result   gf   ga        opponent  ...  \
team                                                                    ...
Arsenal                 4   Sat  Home      W  1.0  0.0    Norwich City  ...
                        5   Sat  Away      W  1.0  0.0         Burnley  ...
                        7   Sun  Home      W  3.0  1.0       Tottenham  ...
                        8   Sat  Away      D  0.0  0.0        Brighton  ...
                        9   Mon  Home      D  2.0  2.0  Crystal Palace  ...
...                         ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 39  Sat  Away      L  0.0  6.0        Brighton  ...
                        40  Sat  Home      W  1.0  0.0     Aston Villa  ...
                        41  Sat  Away      L  0.0  2.0  Manchester Utd  ...
                        42  Sat  Home      D  1.0  1.0         Everton  ...
                        43  Sun  Away      L  0.0  5.0         Arsenal  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 4          5       1    0.000000    3.000000
                        5          5       1    0.333333    2.333333
                        7          6       1    0.666667    1.666667
                        8          5       0    1.666667    0.333333
                        9          0       0    1.333333    0.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 39         5       0    1.666667    0.666667
                        40         5       1    1.000000    2.666667
                        41         5       0    1.000000    2.000000
                        42         5       0    0.333333    2.666667
                        43         6       0    0.666667    1.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 4    9.666667    2.333333    14.833333   0.333333
                        5   12.333333    3.000000    14.133333   0.333333
                        7   14.666667    3.000000    14.800000   0.666667
                        8   18.333333    5.333333    18.433333   0.666667
                        9   11.000000    4.000000    19.833333   0.666667
...                               ...         ...          ...        ...
Wolverhampton Wanderers 39  11.666667    4.666667    18.700000   0.666667
                        40  11.333333    2.333333    18.800000   0.666667
                        41   8.000000    2.000000    17.766667   0.000000
                        42   7.000000    1.333333    15.600000   0.000000
                        43   8.000000    2.333333    15.333333   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 4     0.000000       0.000000
                        5     0.000000       0.000000
                        7     0.000000       0.000000
                        8     0.000000       0.000000
                        9     0.000000       0.000000
...                                ...            ...
Wolverhampton Wanderers 39    0.333333       0.333333
                        40    0.333333       0.333333
                        41    0.333333       0.333333
                        42    0.000000       0.000000
                        43    0.000000       0.000000

[1471 rows x 40 columns]

In [43]:
matches_rolling = matches_rolling.droplevel('team')

In [44]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
7,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
8,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
9,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
41,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1.0,1.0,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0.0,5.0,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [45]:
matches_rolling.index = range(matches_rolling.shape[0])

In [46]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
1,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
2,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
3,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
4,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
1467,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
1468,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
1469,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1.0,1.0,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
1470,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0.0,5.0,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [47]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-04-01']
    test = data[data["date"] > '2023-04-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [48]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [49]:
precision

0.6081081081081081

In [50]:
combined

      actual  predicted
64         0          0
65         0          1
66         0          0
67         0          0
68         1          0
...      ...        ...
1466       0          0
1467       1          0
1468       0          0
1469       0          0
1470       0          0

[226 rows x 2 columns]

In [51]:
combined = combined.merge(matches_rolling[["date","team", "opponent","result"]], left_index = True, right_index = True)

In [52]:
combined

,actual,predicted,date,team,opponent,result
64,0,0,2023-04-09,Arsenal,Liverpool,D
65,0,1,2023-04-16,Arsenal,West Ham,D
66,0,0,2023-04-21,Arsenal,Southampton,D
67,0,0,2023-04-26,Arsenal,Manchester City,L
68,1,0,2023-05-02,Arsenal,Chelsea,W
...,...,...,...,...,...,...
1466,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
1467,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
1468,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L
1469,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D
1470,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L

In [53]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [54]:
mapping["West Ham United"]

'West Ham'

In [55]:
combined["new_team"] = combined["team"].map(mapping)

In [56]:
combined

,actual,predicted,date,team,opponent,result,new_team
64,0,0,2023-04-09,Arsenal,Liverpool,D,Arsenal
65,0,1,2023-04-16,Arsenal,West Ham,D,Arsenal
66,0,0,2023-04-21,Arsenal,Southampton,D,Arsenal
67,0,0,2023-04-26,Arsenal,Manchester City,L,Arsenal
68,1,0,2023-05-02,Arsenal,Chelsea,W,Arsenal
...,...,...,...,...,...,...,...
1466,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
1467,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
1468,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves
1469,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves
1470,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves

In [63]:
combined.to_csv("combined.csv")

In [57]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [58]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2023-04-09,Arsenal,Liverpool,D,Arsenal,0,0,Liverpool,Arsenal,D,Liverpool
1,0,1,2023-04-16,Arsenal,West Ham,D,Arsenal,0,0,West Ham United,Arsenal,D,West Ham
2,0,0,2023-04-21,Arsenal,Southampton,D,Arsenal,0,0,Southampton,Arsenal,D,Southampton
3,0,0,2023-04-26,Arsenal,Manchester City,L,Arsenal,1,1,Manchester City,Arsenal,W,Manchester City
4,1,0,2023-05-02,Arsenal,Chelsea,W,Arsenal,0,0,Chelsea,Arsenal,L,Chelsea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
192,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
193,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd
194,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
195,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [59]:
test

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,0.0,0,0,2023,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,1.0,0,1,2023,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,1.0,0,0,2023,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,0.0,0,0,2023,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,0.0,0,0,2023,Liverpool,0,24,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,0.0,0,0,2023,Southampton,0,16,14,6,0
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,0.0,1,1,2023,Southampton,0,18,20,0,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,0.0,0,0,2023,Southampton,1,9,15,5,0
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,1.0,0,0,2023,Southampton,0,4,14,6,0
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,1.0,0,0,2023,Southampton,1,12,16,6,0

In [60]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

actual_x
1    32
0    20
Name: count, dtype: int64

In [61]:
32/(32+20)

0.6153846153846154

In [62]:
merged.to_csv("merged.csv")